// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDf5baG2MlqXNOchacOVYwKpnZmjdTJlI',
    appId: '1:89262475118:web:a36b2747a34a367e22a37f',
    messagingSenderId: '89262475118',
    projectId: 'healthcare-8ee3f',
    authDomain: 'healthcare-8ee3f.firebaseapp.com',
    storageBucket: 'healthcare-8ee3f.firebasestorage.app',
    measurementId: 'G-YBSNQHMZ4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCph7-CQ_VCOQ27FnWkz-OCz6COolkBDM0',
    appId: '1:89262475118:android:bb88dd166dbc072322a37f',
    messagingSenderId: '89262475118',
    projectId: 'healthcare-8ee3f',
    storageBucket: 'healthcare-8ee3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHlWMQwx0eUdeRLto9Ngt7ig6DIBwrcVU',
    appId: '1:89262475118:ios:160b55971bb3ff0322a37f',
    messagingSenderId: '89262475118',
    projectId: 'healthcare-8ee3f',
    storageBucket: 'healthcare-8ee3f.firebasestorage.app',
    iosBundleId: 'com.example.healthcareapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHlWMQwx0eUdeRLto9Ngt7ig6DIBwrcVU',
    appId: '1:89262475118:ios:160b55971bb3ff0322a37f',
    messagingSenderId: '89262475118',
    projectId: 'healthcare-8ee3f',
    storageBucket: 'healthcare-8ee3f.firebasestorage.app',
    iosBundleId: 'com.example.healthcareapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDf5baG2MlqXNOchacOVYwKpnZmjdTJlI',
    appId: '1:89262475118:web:573a8fe10c95a2ee22a37f',
    messagingSenderId: '89262475118',
    projectId: 'healthcare-8ee3f',
    authDomain: 'healthcare-8ee3f.firebaseapp.com',
    storageBucket: 'healthcare-8ee3f.firebasestorage.app',
    measurementId: 'G-FQP0VYXL2J',
  );
}
